# .woodpecker.yml (Versión CI Final con Sintaxis Corregida)

when:
  branch: main
  event: push

steps:
- name: build-pacientes
  image: woodpeckerci/plugin-docker-buildx
  settings:
    registry: ghcr.io
    repo: ghcr.io/criz8766/proyecto_gps_servidor/pacientes
    username: criz8766
    # --- SINTAXIS CORREGIDA ---
    password:
      from_secret: GITHUB_PAT
    context: pacientes
    dockerfile: pacientes/Dockerfile
    tags:
      - latest
      - ${COMMIT_SHA}

- name: build-inventario
  image: woodpeckerci/plugin-docker-buildx
  settings:
    registry: ghcr.io
    repo: ghcr.io/criz8766/proyecto_gps_servidor/inventario
    username: criz8766
    # --- SINTAXIS CORREGIDA ---
    password:
      from_secret: GITHUB_PAT
    context: inventario
    dockerfile: inventario/Dockerfile
    tags:
      - latest
      - ${COMMIT_SHA}

- name: build-frontend
  image: woodpeckerci/plugin-docker-buildx
  settings:
    registry: ghcr.io
    repo: ghcr.io/criz8766/proyecto_gps_servidor/frontend
    username: criz8766
    # --- SINTAXIS CORREGIDA ---
    password:
      from_secret: GITHUB_PAT
    context: frontend
    dockerfile: frontend/Dockerfile
    tags: [ latest, ${COMMIT_SHA} ]
    # --- LA SECCIÓN CLAVE CON LA SINTAXIS CORRECTA ---
    build_args_from_env:
      - REACT_APP_AUTH0_DOMAIN
      - REACT_APP_AUTH0_CLIENT_ID
      - REACT_APP_AUTH0_API_AUDIENCE