# .woodpecker.yml (Versión Final con Inyección de Secretos)

when:
  branch: main
  event: push

steps:
  build_pacientes:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/pacientes
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: pacientes
      dockerfile: pacientes/Dockerfile
      tags: [ latest ]

  build_inventario:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/inventario
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: inventario
      dockerfile: inventario/Dockerfile
      tags: [ latest ]

  # --- ESTE ES EL PASO CORREGIDO ---
  build_frontend:
    image: woodpeckerci/plugin-docker-buildx
    # 1. Le decimos al paso que necesita acceso a estos secretos
    secrets:
      - GITHUB_PAT
      - REACT_APP_AUTH0_DOMAIN
      - REACT_APP_AUTH0_CLIENT_ID
      - REACT_APP_AUTH0_API_AUDIENCE
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/frontend
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: frontend
      dockerfile: frontend/Dockerfile
      # 2. Inyectamos los secretos como argumentos de construcción
      build_args:
        - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
        - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
        - REACT_APP_AUTH0_API_AUDIENCE=${REACT_APP_AUTH0_API_AUDIENCE}
      tags: [ latest ]