when:
  branch: main
  event: push

steps:
- name: debug-env
  image: alpine
  environment:
    REACT_APP_AUTH0_DOMAIN:
      from_secret: REACT_APP_AUTH0_DOMAIN
    REACT_APP_AUTH0_CLIENT_ID:
      from_secret: REACT_APP_AUTH0_CLIENT_ID
    REACT_APP_AUTH0_API_AUDIENCE:
      from_secret: REACT_APP_AUTH0_API_AUDIENCE
    REACT_APP_PACIENTES_API_URL:
      from_secret: REACT_APP_PACIENTES_API_URL
    REACT_APP_INVENTARIO_API_URL:
      from_secret: REACT_APP_INVENTARIO_API_URL
  commands:
    - |
      echo "=== Variables de entorno React ==="
      echo "Auth0 Domain: $REACT_APP_AUTH0_DOMAIN"
      echo "Client ID: $REACT_APP_AUTH0_CLIENT_ID"
      echo "Audience: $REACT_APP_AUTH0_API_AUDIENCE"
      echo "Pacientes API URL: $REACT_APP_PACIENTES_API_URL"
      echo "Inventario API URL: $REACT_APP_INVENTARIO_API_URL"

- name: build-pacientes
  image: woodpeckerci/plugin-docker-buildx
  settings:
    registry: ghcr.io
    repo: ghcr.io/criz8766/proyecto_gps_servidor/pacientes
    username: criz8766
    password:
      from_secret: GITHUB_PAT
    context: pacientes
    dockerfile: pacientes/Dockerfile
    tags:
      - latest
      - ${COMMIT_SHA}

- name: build-inventario
  image: woodpeckerci/plugin-docker-buildx
  settings:
    registry: ghcr.io
    repo: ghcr.io/criz8766/proyecto_gps_servidor/inventario
    username: criz8766
    password:
      from_secret: GITHUB_PAT
    context: inventario
    dockerfile: inventario/Dockerfile
    tags:
      - latest
      - ${COMMIT_SHA}

- name: build-frontend
  image: woodpeckerci/plugin-docker-buildx
  settings:
    registry: ghcr.io
    repo: ghcr.io/criz8766/proyecto_gps_servidor/frontend
    username: criz8766
    password:
      from_secret: GITHUB_PAT
    context: frontend
    dockerfile: frontend/Dockerfile
    tags:
      - latest
      - ${COMMIT_SHA}
    build_args_from_env:
      - REACT_APP_AUTH0_DOMAIN
      - REACT_APP_AUTH0_CLIENT_ID
      - REACT_APP_AUTH0_API_AUDIENCE
      - REACT_APP_PACIENTES_API_URL
      - REACT_APP_INVENTARIO_API_URL
