# .woodpecker.yml (Versión con Carga de Entorno Explícita)

when:
  branch: main
  event: push

steps:
  # ... (tus tres pasos de build se quedan exactamente igual) ...

  build_pacientes:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/pacientes
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: pacientes
      dockerfile: pacientes/Dockerfile
      tags:
        - latest
        - ${COMMIT_SHA}

  build_inventario:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/inventario
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: inventario
      dockerfile: inventario/Dockerfile
      tags:
        - latest
        - ${COMMIT_SHA}

  build_frontend:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/frontend
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: frontend
      dockerfile: frontend/Dockerfile
      # Esta es la sección clave que faltaba:
      build_args:
        - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
        - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
        - REACT_APP_AUTH0_API_AUDIENCE=${REACT_APP_AUTH0_API_AUDIENCE}
      tags:
        - latest