# .woodpecker.yml (Versión con Carga de Entorno Explícita)

when:
  branch: main
  event: push

steps:
  # ... (tus tres pasos de build se quedan exactamente igual) ...

  build_pacientes:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/pacientes
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: pacientes
      dockerfile: pacientes/Dockerfile
      tags:
        - latest
        - ${COMMIT_SHA}

  build_inventario:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/inventario
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: inventario
      dockerfile: inventario/Dockerfile
      tags:
        - latest
        - ${COMMIT_SHA}

  build_frontend:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/frontend
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: frontend
      dockerfile: frontend/Dockerfile
      tags:
        - latest
        - ${COMMIT_SHA}

  # --- DESPLIEGUE CON CORRECCIÓN FINAL ---
  deploy:
    image: appleboy/drone-ssh
    settings:
      host: 192.168.0.29
      username: arcci
      key: { from_secret: SERVIDOR_PRODUCCION_SSH }
      script:
        - cd /home/arcci/Descargas/proyecto_gps_servidor/proyecto_gps
        - git pull origin main
        - echo "==> Iniciando sesión en GHCR..."
        - cat ~/.github-pat | docker login ghcr.io -u criz8766 --password-stdin
        - echo "==> Descargando las nuevas imágenes..."
        # Le decimos que use el .env
        - docker-compose --env-file .env -f docker-compose.prod.yml pull
        - echo "==> Deteniendo servicios antiguos..."
        # Le decimos que use el .env
        - docker-compose --env-file .env -f docker-compose.prod.yml down --remove-orphans
        - echo "==> Iniciando nuevos servicios..."
        # Le decimos que use el .env
        - docker-compose --env-file .env -f docker-compose.prod.yml up -d
        - echo "==> Limpiando imágenes antiguas..."
        - docker image prune -af