# .woodpecker.yml (Versión Final con Sintaxis Corregida y Funcional)

when:
  branch: main
  event: push

steps:
- name: build-pacientes
  image: woodpeckerci/plugin-docker-buildx
  settings:
    registry: ghcr.io
    repo: ghcr.io/criz8766/proyecto_gps_servidor/pacientes
    username: criz8766
    password:
      from_secret: GITHUB_PAT
    context: pacientes
    dockerfile: pacientes/Dockerfile
    # --- SINTAXIS CORREGIDA ---
    tags:
      - latest
      - ${COMMIT_SHA}

- name: build-inventario
  image: woodpeckerci/plugin-docker-buildx
  settings:
    registry: ghcr.io
    repo: ghcr.io/criz8766/proyecto_gps_servidor/inventario
    username: criz8766
    password:
      from_secret: GITHUB_PAT
    context: inventario
    dockerfile: inventario/Dockerfile
    # --- SINTAXIS CORREGIDA ---
    tags:
      - latest
      - ${COMMIT_SHA}

- name: build-frontend
  image: woodpeckerci/plugin-docker-buildx
  settings:
    registry: ghcr.io
    repo: ghcr.io/criz8766/proyecto_gps_servidor/frontend
    username: criz8766
    password:
      from_secret: GITHUB_PAT
    context: frontend
    dockerfile: frontend/Dockerfile
    # --- SINTAXIS CORREGIDA ---
    tags:
      - latest
      - ${COMMIT_SHA}
    build_args_from_env:
      - REACT_APP_AUTH0_DOMAIN
      - REACT_APP_AUTH0_CLIENT_ID
      - REACT_APP_AUTH0_API_AUDIENCE