# .woodpecker.yml (Versión Final y Simplificada)

when:
  branch: main
  event: push

steps:
  build_and_push_pacientes:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/pacientes
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: pacientes  # <-- Le decimos que trabaje aquí
      tags:
        - latest
        - ${COMMIT_SHA}

  build_and_push_inventario:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/inventario
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: inventario # <-- Le decimos que trabaje aquí
      tags:
        - latest
        - ${COMMIT_SHA}

  build_and_push_frontend:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io
      repo: ghcr.io/criz8766/proyecto_gps_servidor/frontend
      username: criz8766
      password: { from_secret: GITHUB_PAT }
      context: frontend # <-- Le decimos que trabaje aquí
      tags:
        - latest
        - ${COMMIT_SHA}

  # El paso de despliegue se ejecuta solo si los anteriores tienen éxito
  deploy_to_server:
    image: appleboy/drone-ssh
    settings:
      host: 192.168.0.29
      username: arcci
      key: { from_secret: SERVIDOR_PRODUCCION_SSH }
      script:
        - cd /home/arcci/Descargas/proyecto_gps_servidor/proyecto_gps
        - git pull origin main
        - cat ~/.github-pat | docker login ghcr.io -u criz8766 --password-stdin
        - docker-compose -f docker-compose.prod.yml pull
        - docker-compose -f docker-compose.prod.yml down --remove-orphans
        - docker-compose -f docker-compose.prod.yml up -d
        - docker image prune -af