# docker-compose.prod.yml (Versión Final Corregida)

version: '3.8'

services:
  # Jenkins YA NO ESTÁ AQUÍ. Solo están los servicios de la aplicación.
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:2.8.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  pacientes:
    image: ghcr.io/criz8766/proyecto_gps_servidor/pacientes:latest
    container_name: pacientes
    depends_on:
      - postgres
      - kafka
    environment:
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_API_AUDIENCE: ${AUTH0_API_AUDIENCE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ALLOWED_ORIGINS: http://localhost:3000,https://sga.arccidev.com
    ports:
      - "8000:8000"

  inventario:
    image: ghcr.io/criz8766/proyecto_gps_servidor/inventario:latest
    container_name: inventario
    depends_on:
      - postgres
      - kafka
    environment:
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_API_AUDIENCE: ${AUTH0_API_AUDIENCE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ALLOWED_ORIGINS: http://localhost:3000,https://sga.arccidev.com
    ports:
      - "8001:8001"

  frontend:
    image: ghcr.io/criz8766/proyecto_gps_servidor/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - pacientes
      - inventario

volumes:
  pgdata:
  mongodata: