# .github/workflows/ci-pipeline.yml (Versión Final y Definitiva)

name: CI - Construir y Publicar Imágenes Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # --- CORRECCIÓN FINAL ---
      # Usamos el nuevo PAT para iniciar sesión, no el GITHUB_TOKEN
      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} # <-- ¡ESTE ES EL CAMBIO!

      # Los pasos de build se quedan exactamente igual
      - name: Construir y subir imagen de pacientes
        uses: docker/build-push-action@v5
        with:
          context: ./pacientes
          file: ./pacientes/Dockerfile
          push: true
          tags: ghcr.io/criz8766/proyecto_gps_servidor/pacientes:latest

      - name: Construir y subir imagen de inventario
        uses: docker/build-push-action@v5
        with:
          context: ./inventario
          file: ./inventario/Dockerfile
          push: true
          tags: ghcr.io/criz8766/proyecto_gps_servidor/inventario:latest

      - name: Construir y subir imagen de usuarios
        uses: docker/build-push-action@v5
        with:
          context: ./usuarios
          file: ./usuarios/Dockerfile
          push: true
          tags: ghcr.io/criz8766/proyecto_gps_servidor/usuarios:latest

      - name: Construir y subir imagen de frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/criz8766/proyecto_gps_servidor/frontend:latest
          build-args: |
            REACT_APP_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
            REACT_APP_AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
            REACT_APP_AUTH0_API_AUDIENCE=${{ secrets.AUTH0_API_AUDIENCE }}
            REACT_APP_PACIENTES_API_URL=/api/pacientes
            REACT_APP_INVENTARIO_API_URL=/api/inventario